use_frameworks!

target 'WYCommonFramework_Example' do
  pod 'WYCommonFramework', :path => '../'
  pod 'FDFullscreenPopGesture'

  target 'WYCommonFramework_Tests' do
    inherit! :search_paths

    
  end
end
